// For Personal Care-
export const REQUEST_PERSONAL_CARE = "REQUEST_PERSONAL_CARE";
export const SUCCESS_PERSONAL_CARE = "SUCCESS_PERSONAL_CARE";
export const ERROR_PERSONAL_CARE = "ERROR_PERSONAL_CARE";

