// For Bisuit Snacks and Chocklates -
export const REQUEST_BISCUIT_SNACKS_CHOCKLATES = "REQUEST_BISCUIT_SNACKS_CHOCKLATES";
export const SUCCESS_BISCUIT_SNACKS_CHOCKLATES = "SUCCESS_BISCUIT_SNACKS_CHOCKLATES";
export const ERROR_BISCUIT_SNACKS_CHOCKLATES = "ERROR_BISCUIT_SNACKS_CHOCKLATES";
