// For Chemist Store-
export const REQUEST_CHEMIST_STORE = "REQUEST_CHEMIST_STORE";
export const SUCCESS_CHEMIST_STORE = "SUCCESS_CHEMIST_STORE";
export const ERROR_CHEMIST_STORE = "ERROR_CHEMIST_STORE";
